### ISSUE TITLE
(Idea) Update for MagicaVoxel 0.99.7

### ISSUE THREAD

**Issue by InnovativeName-GameDev** [technistguru/MagicaVoxel_Importer#2]
There is at least currenttly a beta of magica voxel with a new update to the file extension. The Updater is currently unable to import these. I want to ask, if the importer will be updated when the Magicavoxel update is out of the Beta phase.

**Comment by Texnist** [comment]
Sorry, I won't be able to continue maintaining this add-on so unless someone else wants to work on it the answer is no.

**Comment by HexStar27** [comment]
> There is at least currenttly a beta of magica voxel with a new update to the file extension.

What's the version of that beta? 99.7?
